### ISSUE TITLE
Search bar switches back to Check out each page load

### ISSUE THREAD

**Issue by benjaminwd** [jajm/koha-staff-interface-redesign#1]
When searching, the search bar switches back to check out on each page load. So if I do a catalog search, the search bar should stay on catalog search rather than switching back to Check out.

**Comment by kfischer** [comment]
I've done some tests:

- Catalog search reloads and catalog search remains open
- Patron search reloads and patron search remains open (if more than one result is found)

Looks good to me now!

**Comment by jajm** [comment]
Thanks for testing!
