### ISSUE TITLE
Patron selection toolbar displays before search regression

### ISSUE THREAD

**Issue by mrenvoize** [jajm/koha-staff-interface-redesign#12]
The select actions toolbar now appears on initial page load for the `Patrons` module now, this is a regression.

![screenshot-mrdev-zebra-staff koha-ptfs co uk-2022 08 15-08_30_51](https://user-images.githubusercontent.com/557612/184594327-a380a600-81fe-4cbe-9bdd-0f27d6f33820.png)

**Comment by joubu** [comment]
Nope, this is in master. See https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30416
