### ISSUE TITLE
'Clear filters' feels mis-aligned

### ISSUE THREAD

**Issue by mrenvoize** [jajm/koha-staff-interface-redesign#16]
Whilst I think the other options on a datatables table make sense to get pushed to the right, I think the 'Clear filters' option makes most sense directly next to the search box that's left aligned next to the table details.

Perhaps we could even replace 'Clear filters' with just an 'X' inside the search box and a tooltip for the written explanation?

Before
![dt_options_before](https://user-images.githubusercontent.com/557612/188173538-d4a7428d-7534-4a67-8629-fcf68efd0b02.png)

After
![dt_options_after](https://user-images.githubusercontent.com/557612/188173564-5150e320-97e1-4e6d-a9cb-323ffc00c783.png)

**Comment by kfischer** [comment]
I wasn't sure where Martin's screenshot was from, so looked in Administration > Itemtypes:

![grafik](https://user-images.githubusercontent.com/425526/189678583-e2d2001c-d44d-440d-b1fa-b3f9403724b0.png)

Sequence is better, but things are not where they should be. 

Also the clear filter has a lighter background color, while the other options have no background color.

**Comment by jajm** [comment]
> Sequence is better, but things are not where they should be.

Of course not all table headers have the same HTML markup :)
This should be fixed now

> Also the clear filter has a lighter background color, while the other options have no background color.

Also fixed

**Comment by kfischer** [comment]
Looked at some random tables, it's overall nicely looking now:

![grafik](https://user-images.githubusercontent.com/425526/190092969-5cbddfe9-b826-489b-b939-7bddc07c5d3a.png)

![grafik](https://user-images.githubusercontent.com/425526/190093115-d6003661-b3f5-4391-98f0-4008d580c03c.png)

![grafik](https://user-images.githubusercontent.com/425526/190093287-13848874-e6fa-4435-8cfa-f03395c2465b.png)

**Comment by jajm** [comment]
Thanks for testing!
I'm closing this one. Feel free to reopen if you find a a table where it's not correctly aligned
