### ISSUE TITLE
"Card" inconsistency with the mockups

### ISSUE THREAD

**Issue by mrenvoize** [jajm/koha-staff-interface-redesign#17]
The mock-up on page 9 of the slides showed a nice consistent set of 'Cards' used for page sections.. this hasn't translated through to the current display for checkouts at least.

![card_inconsistency](https://user-images.githubusercontent.com/557612/188418622-55d2b814-af26-413e-a702-e801907b0b6a.png)

compared to

![cards_mockup](https://user-images.githubusercontent.com/557612/188418881-a0aaf632-1925-4c09-a69d-eacd366ed4e3.png)

- [x] The 'Checkout out to patron' card layout isn't laid out as expected and the action button isn't highlighted yellow.

- [x] The 'Messages' area isn't in a card layout (and I'm not sure what/how the other patron info that can appear in this area should display.. in their own card(s) or as part of the 'Messages' card we're introducing?
- [ ] The 'tabs' below are not "Pills inside a card" as the mock-up showed?

**Comment by kfischer** [comment]
I am not fond of the dark green border and I think the 'pills' would give it a much lighter and nicer look maybe.  

On the other hand tabs are something that are described in a lot of the instructions/manuals and they are a well known GUI element people know to look for. 

Maybe there is a compromise without the green border line?

**Comment by mrenvoize** [comment]
Remainder of this one opened as [Bug 31759](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31759) - Tabs vs Pills
