### ISSUE TITLE
Circulation start page: Usability of links vs buttons

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#18]
The current circulation start page like the Koha start page has big clickable buttons. The new interface replaces these by links, which are much harder to target, especially on touch displays. It's also creates a design inconsistency between the different start pages.

Before:
![grafik](https://user-images.githubusercontent.com/425526/189327011-a7294a5a-23fb-49a6-a787-f758d48f917d.png)

After:
![grafik](https://user-images.githubusercontent.com/425526/189327139-69f7cb7d-235c-4a72-ad05-ef28ab1a02af.png)

**Comment by mrenvoize** [comment]
With the cataloguing home page redesign I've been working on I've been moving us towards more button-based homepages...

**Comment by kfischer** [comment]
> With the cataloguing home page redesign I've been working on I've been moving us towards more button-based homepages...

That's correct. So in order to be consistent, that would be another +1 for buttons :)

**Comment by jajm** [comment]
I tried something
![image](https://user-images.githubusercontent.com/306836/189681382-5d7cf2c6-3450-438e-9e40-e6f5da35b2c3.png)

and applied that to the home page as well
![image](https://user-images.githubusercontent.com/306836/189681670-ee0490aa-eff6-48bf-a649-d0c58b47a75e.png)

Let me know what you think

**Comment by mrenvoize** [comment]
Really like the consistency added there

**Comment by kfischer** [comment]
I like the new style of those pages too :)

**Comment by jajm** [comment]
Cool :)
Thanks for testing
