### ISSUE TITLE
Entry in search bar does not persist across searches

### ISSUE THREAD

**Issue by benjaminwd** [jajm/koha-staff-interface-redesign#2]
When I enter something into the search bar and realize I'm in the wrong context, the entry does not persist when I switch contexts. So if I accidentally enter a catalog search into the "Check out" box, when I switch to "Catalog search", the entry should still be there.

**Comment by jajm** [comment]
Looks like the `keep_text` class was deleted. It should be re-added

**Comment by kfischer** [comment]
Is this testable on the sandboxes? It doesn't yet work for me.

**Comment by kfischer** [comment]
This appears to work ok now on the new sandbox with the latest patches. The search term remains in the input, no matter which search option is activated.

**Comment by jajm** [comment]
Thanks for testing!
