### ISSUE TITLE
Links in result list paging have wrong color

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#21]
On the results list, the paging links have the wrong color:

![grafik](https://user-images.githubusercontent.com/425526/189331540-555f9163-5f66-4814-9ef1-24ba492b06cf.png)

**Comment by mrenvoize** [comment]
I also find the buttons buttons vs dropdown buttons highlighted above odd.

**Comment by kfischer** [comment]
Links now have the right color/background:

![grafik](https://user-images.githubusercontent.com/425526/190098691-a74b90fb-dbb2-417a-aa96-a28680cc055b.png)

@mrenvoize maybe a separate issue for the toolbar?
