### ISSUE TITLE
Search bar / Input area and pull downs

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#24]
The input for searching is a little too small with both  and activated.

I had entered "The Arden edition of the works" and only a small part of the search is still visible. As we don't know how long the library names and search options in translation might get, maybe a minimum with?

The pull downs could be marked a little clearer, so you see where to type a little better.

![grafik](https://user-images.githubusercontent.com/425526/189356010-4961f071-f901-46ff-b58b-2ffefc6efe82.png)

**Comment by kfischer** [comment]
Because this is a chance too: I quite like the last iteration of the search bar - it's certainly improving which each iteration!

**Comment by mrenvoize** [comment]
I'm not a fan of the inconsistency of some searches having inline selects and others having the 'options' button.

This is what Owen did for this search one and I think I prefer it.. would it satisfy your needs too Katrin?

![screenshot-staff-bug30952o sandboxes biblibre eu-2022 09 09-14_53_08](https://user-images.githubusercontent.com/557612/189366196-548b8f45-99bf-480f-96bf-f96c8a250134.png)

**Comment by kfischer** [comment]
I have thought about it, it certainly looks nice, but it's another click compared to how it works on master now. That's why I think maybe we should go with the inline one.

**Comment by mrenvoize** [comment]
I had a feeling you might say that.. I really do dislike inconsistency though...

![screenshot-staff-bug30952r sandboxes biblibre eu-2022 09 09-15_56_32](https://user-images.githubusercontent.com/557612/189379983-296d0896-1349-44bd-9d32-3147cb21b33d.png)

**Comment by jajm** [comment]
I'm not sure what to do here... Should we have all forms inline ? With the 5 inputs of the patron search, it will be a bit long.

**Comment by mrenvoize** [comment]
@oleonard any thoughts/advice on this one?

**Comment by oleonard** [comment]
I think the multiple inline fields option has never worked well even with the current staff interface design. I would much prefer that we get the users used to the option of an expanded view. I actually like that this would let us eliminate the  IntranetAddMastheadLibraryPulldown and  IntranetCatalogSearchPulldown preferences.

We already have this pattern in place now with the [+] options on a couple of places like the patron search form.

**Comment by kfischer** [comment]
> I think the multiple inline fields option has never worked well even with the current staff interface design. I would much prefer that we get the users used to the option of an expanded view. I actually like that this would let us eliminate the IntranetAddMastheadLibraryPulldown and IntranetCatalogSearchPulldown preferences.
> 
> We already have this pattern in place now with the [+] options on a couple of places like the patron search form.

You make some valid points. I think I am persuaded and pro expanded now.

Maybe if people complain about extra click there could be some way to 'auto-expand'? (for later)

**Comment by kfischer** [comment]
I am not sure if we should start filing different issues for different things now or keep them all same place for easier discussion, so here it goes:

**Additional search option for catalog search**

- On the start page they show inline, but not at all in another module with catalog search (might still be work in process). At the moment I think we are leaning towards the expand button like for patron search for catalog search too. 
- The search input field is now very wide on a big screen, which adds to the 'distances' you have to go to change options or choose the expand and also it's out of immediate sight. Maybe adding a maxwidth would be nice, still keeping it generously wide, but not as wide as now :)

![grafik](https://user-images.githubusercontent.com/425526/190116265-e2721afd-1f1c-430a-b2b0-ed6cbe9d7bae.png)

![grafik](https://user-images.githubusercontent.com/425526/190116156-7b090145-5c37-4d1c-b906-fec54b82c3a3.png)

**Small screens**

We need to come up with something that works on small screens, because right now it doesn't:

- Input field shrinks to be unusable
- Options don't all display (maybe just show icons on the right on small screens and only full label left?)

![grafik](https://user-images.githubusercontent.com/425526/190115343-389aace0-bb96-418e-8acd-aa834f2628ef.png)

**Comment by jajm** [comment]
New toolbar:
![image](https://user-images.githubusercontent.com/306836/190361611-e17ec759-4444-4200-8010-1981a45e3464.png)
![image](https://user-images.githubusercontent.com/306836/190361742-a1f586e7-669f-4c5e-9720-31b42c36647e.png)
![image](https://user-images.githubusercontent.com/306836/190361804-e3921bb3-665b-47a3-b9c8-b99c0acefeab.png)
![image](https://user-images.githubusercontent.com/306836/190361957-f3d6e36b-7b71-40cd-ad94-c423dba7eb46.png)

**Comment by kfischer** [comment]
Very nice!

**Comment by jajm** [comment]
Closing this. Please reopen if you spot a problem with the search bar
