### ISSUE TITLE
Search results don't use full screen width

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#25]
This is only visible for some searches, but not for all, depending on the max length of titles. In the sample database a keyword search for "Henry" will show the issue:

![grafik](https://user-images.githubusercontent.com/425526/189357311-ebdb4f59-02a4-405f-83f0-a82aba17670b.png)

**Comment by mrenvoize** [comment]
I spotted this too.. but I don't think that's a new issue that is introduced here.. the new formatting just perhaps makes it stand out more... for me this is the same on master so I reckon it can be dealt with as it's own bug ;P

**Comment by jajm** [comment]
I confirm that master has the same problem
Closing this issue

**Comment by kfischer** [comment]
Moved to bugzilla: [Bug 31559](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31559) - Staff results page doesn't always use up full available screen width
