### ISSUE TITLE
Spacing below legends often too small

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#27]
For legends the spacing between content and legend is often a bit too small, but not always. So there are some inconsistencies:

![grafik](https://user-images.githubusercontent.com/425526/189359343-495265d9-58f5-4760-8a3d-1d6084d88e8f.png)

Patron restrictions look ok, but Patron messaging preferences and Additional attributes appear squashed.

**Comment by kfischer** [comment]
There is another good example where we can see the different spacing: Advanced search

![grafik](https://user-images.githubusercontent.com/425526/189888049-d2537b6f-86c5-4525-8e31-e91db551ccdb.png)

**Comment by kfischer** [comment]
This looks much better! I checked patron edit form and the advanced search. Will make another issue for something else on the advanced search page.

**Comment by jajm** [comment]
I think #41 is related to the fix here. Leaving it open for now

**Comment by jajm** [comment]
#41 is fixed. Closing this one now
