### ISSUE TITLE
White area below toolbar on patron details tab

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#28]
Best to explain with a screenshot: I believe the white bar below the toolbar should not be there:

![grafik](https://user-images.githubusercontent.com/425526/189360029-94d13ff7-1bdf-4a7f-9746-f26c54fd4bd9.png)

**Comment by mrenvoize** [comment]
Inspecting the page, this appears to be related to the 'messages' block.. perhaps a template issue including an empty div instead of removing it entirely if there are no messages?

**Comment by jajm** [comment]
> Inspecting the page, this appears to be related to the 'messages' block.. perhaps a template issue including an empty div instead of removing it entirely if there are no messages?

Exactly. It's fixed now

**Comment by kfischer** [comment]
Confirmed fixed :)

**Comment by jajm** [comment]
Thanks!
