### ISSUE TITLE
News entries missing bullet point for lists

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#29]
In the sample news entries there is an unordered list, but we no longer show bullet points. We should bring them back:

![grafik](https://user-images.githubusercontent.com/425526/189361655-402f524e-50c7-4aec-a53b-d46f28a387d1.png)

**Comment by kfischer** [comment]
Works!

![grafik](https://user-images.githubusercontent.com/425526/190137894-7a16926f-ad32-490a-a737-94ed8151fd4f.png)

**Comment by jajm** [comment]
Thanks!
