### ISSUE TITLE
Floating search options header has transparent background

### ISSUE THREAD

**Issue by benjaminwd** [jajm/koha-staff-interface-redesign#3]
The background of the floating search header is transparent, so scrolling down obscures the content of the header.

**Comment by jajm** [comment]
Can you post a screenshot ? I don't see any problems with the search header when scrolling

**Comment by kfischer** [comment]
![grafik](https://user-images.githubusercontent.com/425526/189324200-acb55b00-a3ca-46a3-9f84-0f8d484c55de.png)

Checked the sandbox with the original patches and Owen's additions, the issue appears in both.

**Comment by jajm** [comment]
Thanks, I wasn't looking at the right header :)

**Comment by kfischer** [comment]
Transparency issue is now fixed!

**Comment by jajm** [comment]
Thanks for testing! :)
