### ISSUE TITLE
Sidebars / Highlighting different sections

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#30]
At the moment the sidebars use lines below the headings to highlight different sections.

![grafik](https://user-images.githubusercontent.com/425526/189363064-bc3e6f53-ab0e-4174-a37d-c48912dfe7e4.png)

* The top of the sidebar appears 'cut off' at the moment.
* I am not so keen on the lines as most of the layout works without lines and these feel a bit too strong here. For me it looks like the section goes from line to line, instead of the line starting an entry. And I feel like it conflicts with the nice cutout for the selected page. If that makes sense? Maybe just working with font-size and some indentation would be nicer.

**Comment by mrenvoize** [comment]
This came up in the ptfs-e testing too.. though we weren't sure on how to improve it yet.. just that it felt off somehow.

**Comment by jajm** [comment]
It looks like this now:
![image](https://user-images.githubusercontent.com/306836/189916302-4fb0fa9d-c93e-44bc-90fa-89bba90d5d63.png)

**Comment by kfischer** [comment]
I think it's much better (hope others agree too!)

**Comment by kfischer** [comment]
To have another example for people to look at: Administration

![grafik](https://user-images.githubusercontent.com/425526/190092175-9bfd9d7a-6808-4606-be2a-16f69bedc8ed.png)

**Comment by mrenvoize** [comment]
Excellent improvement.

**Comment by jajm** [comment]
Thanks for testing/feedback
