### ISSUE TITLE
Edit/Add item form layout is broken

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#31]
First major issue I have encountered:
![grafik](https://user-images.githubusercontent.com/425526/189366717-d61cedd0-2c7b-4261-a54d-21f48f93049d.png)

Note: The button for adding multiple items at the bottom of the form doesn't look quite right either and has no hover.

**Comment by kfischer** [comment]
Fix confirmed!

**Comment by jajm** [comment]
Thanks!
