### ISSUE TITLE
Search headers collection - Comment not bug

### ISSUE THREAD

**Issue by mrenvoize** [jajm/koha-staff-interface-redesign#33]
I wanted to check all the search bar types and it surprised me to find how many different one's we have.. so I thought I'd collect them in screenshots here.

## Home
![home_search](https://user-images.githubusercontent.com/557612/189392079-af8fbfaf-dca4-4cca-8f72-f298a0f08892.png)
## Circulation
![circulation_search](https://user-images.githubusercontent.com/557612/189392077-2e09dec1-346f-4990-97c2-f44eb1d82929.png)
## Patrons
![patrons_search](https://user-images.githubusercontent.com/557612/189392073-ba47227d-08eb-41b3-bced-be4db054c4d9.png)
## Advanced
![advanced_search](https://user-images.githubusercontent.com/557612/189392069-f11103ed-e7a5-47df-b391-93c4f699489c.png)
## Authorities
![authories_search](https://user-images.githubusercontent.com/557612/189392065-2aeac487-2d70-4313-a48a-a7ddcd76bbe6.png)
## Cataloguing
![catalogueing_search](https://user-images.githubusercontent.com/557612/189392063-0b19275d-7984-4d1c-8102-a562ec68d9e5.png)
## Serials
![serials_search](https://user-images.githubusercontent.com/557612/189392060-3288a2dc-67e0-420d-aea3-6358d1d44109.png)
## Acquisitions
![acquisitions_search](https://user-images.githubusercontent.com/557612/189392059-3cbd5bdf-0f64-42d4-99b7-c5dd15af931e.png)
## Lists
![lists_search](https://user-images.githubusercontent.com/557612/189392068-419fb0f6-dac6-4c52-9d13-9e0d4b64c4ae.png)
## Administration
![administration_search](https://user-images.githubusercontent.com/557612/189392054-db9cef70-d59f-453c-9499-bcde10ceb8dd.png)

**Comment by mrenvoize** [comment]
This is for another day.. but I love to see us go through these and see if there's any way to ratify them a bit.. I'm sure we don't need this many variations and inconsistencies.

**Comment by kfischer** [comment]
The module specific searches are needed I think, but within a module they should probably be the same. We should also have the same formatting etc.

**Comment by mrenvoize** [comment]
I agree.. there are subtle formatting differences and changes to the order of the search types.  I don't think we need to deal with it within the scope of this bug though.. just thought it worth recording for a quick follow-up down the line.

**Comment by mrenvoize** [comment]
Kill this one off if you like @jajm.. it's noise and I'm happy to play in BZ later.

**Comment by jajm** [comment]
As you wish :)
