### ISSUE TITLE
Patron edit actions should follow general style for save/cancel options

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#36]
When editing a patron, the save/cancel are quite hard to spot in light grey at the top. These should follow the styling of other save buttons with yellow save button and green link cancel:

![grafik](https://user-images.githubusercontent.com/425526/190101593-49a2baca-f4eb-4420-877e-972e9ca08d38.png)

![grafik](https://user-images.githubusercontent.com/425526/190101492-cc4c6bf8-57ad-441b-8133-9b3dff9fd8ce.png)

**Comment by jajm** [comment]
This is fixed
![image](https://user-images.githubusercontent.com/306836/190368075-71f180db-ed2d-4796-a64e-af20992b90a5.png)

**Comment by kfischer** [comment]
Much better, thanks! 

I was wondering, why the script looked a little fuzzy/blurred in your screenshot. It looks like there is still some shadow, maybe we could remove that:

![grafik](https://user-images.githubusercontent.com/425526/191023370-410eee31-e2a4-4c65-9e44-66575fbd4fd6.png)

**Comment by jajm** [comment]
I opened a new issue for the blurred text (#49)
Closing this one
