### ISSUE TITLE
Menu link in the top bar needs to be white on small screens

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#37]
When looking at the new GUI on a small screen, the menu icon has now green link text, which has no good contrast. It should be white as the other entries there on bigger screens.

(search bar issue will be filed separately)

![grafik](https://user-images.githubusercontent.com/425526/190113652-1e058653-5922-4483-b91d-e706246426e6.png)

**Comment by kfischer** [comment]
Fixed!

**Comment by jajm** [comment]
Thanks for testing!
