### ISSUE TITLE
Toolbar 'Link' buttons and 'Select' buttons are styled differently

### ISSUE THREAD

**Issue by mrenvoize** [jajm/koha-staff-interface-redesign#39]
Extracted from issue #21, the toolbars contain two differently styled 'Buttons' now, I think we should restore some more consistent styling of these elements.. though at this point I'm not sure which way to go..

![Toolbar](https://user-images.githubusercontent.com/425526/189331540-555f9163-5f66-4814-9ef1-24ba492b06cf.png)

**Comment by mrenvoize** [comment]
@oleonard another one where it might benefit from your UX expertise?

**Comment by jajm** [comment]
master version for comparison:
![image](https://user-images.githubusercontent.com/306836/190129948-fcee2910-8b47-4771-b4bc-006ceb52eee9.png)

**Comment by mrenvoize** [comment]
Oh, thanks @jajm, I hadn't appreciated we have a similar inconsistency on master.. now that draws my eye to there being three distinct element types there.. the filters appearing as plain links, the action buttons appearing as buttons and the select/options appearing as buttons with a dropdown caret.

**Comment by jajm** [comment]
It went back to normal

![image](https://user-images.githubusercontent.com/306836/190365201-cbe78ef8-16ba-46b3-98bd-b88f4df5b5a0.png)

**Comment by mrenvoize** [comment]
Confirmed, this looks much clearer to me, thanks @jajm.  Any further refinements to this area I reckon can be done as new bugs later down the line :)

**Comment by jajm** [comment]
Thanks for testing!
