### ISSUE TITLE
Facets / Styling

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#40]
- I think there is no padding/margin to the left and that makes the first letters of the heading almost look a little cut-off on my screen (not so much on the screenshot actually)
- The green 'Refine your search' could maybe be changed up a bit. Also wonder if we should use the grey background here we have in other places on the left side? (sidebars, tabs, etc.)

![grafik](https://user-images.githubusercontent.com/425526/190134766-1e9520fe-2ad0-4ae5-a54d-da8df72192a3.png)

**Comment by jajm** [comment]
Used the same green/grey as everywhere else and increased padding

![image](https://user-images.githubusercontent.com/306836/190360583-481d3566-5089-4309-aee3-043a15aec469.png)

**Comment by kfischer** [comment]
Nice!

**Comment by jajm** [comment]
Thanks for testing!
