### ISSUE TITLE
Additional patron attributes section in patron edit escaped

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#41]
"escaped" outside of the screen:

![grafik](https://user-images.githubusercontent.com/425526/190136283-b22c088a-298f-4bd2-95f1-e802b2d9b1e2.png)

**Comment by kfischer** [comment]
They have been caught now and are showing up int he right spot again :)

**Comment by jajm** [comment]
Thanks for testing!
