### ISSUE TITLE
Advanced search / Location and availability

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#42]
Currently the section looks like this:

![grafik](https://user-images.githubusercontent.com/425526/190136828-91a771d4-6a72-46df-a4fb-9bce17d22737.png)

And I think while the borders have been removed, there is still a lot of whitespace just in this section, it could take up much less space:

![grafik](https://user-images.githubusercontent.com/425526/190137062-07d83aeb-06aa-4710-a96b-55ed9a44b332.png)

**Comment by jajm** [comment]
I removed the padding of nested fieldset so it should be a bit better

![image](https://user-images.githubusercontent.com/306836/190339124-9b65c893-91fb-41c1-8f2f-9f47bb37951d.png)

We still need space between both in case you can limit by library groups

![image](https://user-images.githubusercontent.com/306836/190339401-0aa310bf-5b11-4b36-8995-069cce254f3e.png)

**Comment by kfischer** [comment]
The form has come along nicely now :)

**Comment by jajm** [comment]
Thanks for testing!
