### ISSUE TITLE
Advanced search missing spacing between itemtypes and subtype limits

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#43]
These 2 elements are directly above each other, missing the spacing between sections we have on other parts of the form:

![grafik](https://user-images.githubusercontent.com/425526/190137279-dbc4c3d4-f301-4880-9f67-1e2e5cfbd6d1.png)

**Comment by kfischer** [comment]
Looking nice now overall!

**Comment by jajm** [comment]
Thanks for testing!
