### ISSUE TITLE
Advanced search / Style of floating toolbar

### ISSUE THREAD

**Issue by kfischer** [jajm/koha-staff-interface-redesign#44]
Similar to the issue filed for patron edit, the search buttom should be yellow on the advanced search, following the pattern on other forms for the main action:

![grafik](https://user-images.githubusercontent.com/425526/190137636-ca6d5acd-f5db-489b-b884-7cc53819b89d.png)

**Comment by jajm** [comment]
This was fixed in c8a263e1bc9f87ea68bc568a4306982fc5b30dbd

**Comment by kfischer** [comment]
Stands out much better, thanks!

![grafik](https://user-images.githubusercontent.com/425526/191020905-3ef064e2-6532-4a8d-b7c3-a14f2621424a.png)

**Comment by jajm** [comment]
Thanks for testing!
