### ISSUE TITLE
"Card" inconsistency in biblio display

### ISSUE THREAD

**Issue by mrenvoize** [jajm/koha-staff-interface-redesign#45]
With the addition of a card layout to the Patron module pages, I think for consistency it would be nice to add such cards to Biblio details pages too..

![screenshot-staff-gui sandboxes biblibre eu-2022 09 14-14_49_09](https://user-images.githubusercontent.com/557612/190172330-e8fd90b5-b29f-4231-a81a-7820e614bf3c.png)

vs

![screenshot-staff-gui sandboxes biblibre eu-2022 09 14-14_51_51](https://user-images.githubusercontent.com/557612/190172903-87fc1f1e-6c11-4519-8aac-e6df4e43a134.png)

**Comment by mrenvoize** [comment]
This is perhaps another one out of scope of the initial styling work.. however I thought it worth mentioning as it may be the right time to consider it.. right now it appears we're using a 'patroninfo-section' class for styling this on the patron pages.. maybe a more generic 'info-section' or something class would be beneficial to use more globally?

Happy to open this as a distinct bug to track the markup change it may require as a separate piece of work though.. let me know if you think that's more appropriate.

**Comment by kfischer** [comment]
Not sure what is meant by adding the 'cards' on the detail page and what this would look like. What do you think about #48?

**Comment by mrenvoize** [comment]
By 'Card' I mean 'box' around each content area on the page with a white background... so in the above images the 'Contact information' stuff is all in a 'Card'.. I could envisage the biblio details stuff all being in their own 'Card' too for consistency.

**Comment by kfischer** [comment]
So should the main content always appear in a card?

**Comment by mrenvoize** [comment]
> So should the main content always appear in a card?

Card or Cards in my opinion.. it gives a nice clear distinction for 'sections' of the page.

**Comment by kfischer** [comment]
I am not sure really how well that would work really, where is lots more page where this might play a role then.

**Comment by jajm** [comment]
I added a CSS class `page-section` that can be reused everywhere it's needed. I didn't use the word 'card' because it would conflict with Bootstrap 4 cards (in case of upgrade)

![image](https://user-images.githubusercontent.com/306836/192465061-9c2c31cd-40ef-427a-8669-e863d2171124.png)

**Comment by mrenvoize** [comment]
Thanks @jajm, I think this brings us a step closer... I think I'd keep the overall page heading outside of the page-section div for consistency.. but that's an easy follow-up I'd be happy to submit later.

**Comment by jajm** [comment]
> Thanks @jajm, I think this brings us a step closer... I think I'd keep the overall page heading outside of the page-section div for consistency.. but that's an easy follow-up I'd be happy to submit later.

I'm not sure if it can be done, as the title is part of the result of XSLT processing.

**Comment by mrenvoize** [comment]
> > Thanks @jajm, I think this brings us a step closer... I think I'd keep the overall page heading outside of the page-section div for consistency.. but that's an easy follow-up I'd be happy to submit later.
> 
> I'm not sure if it can be done, as the title is part of the result of XSLT processing.

Good point.. I hadn't realized that.. Certainly not one to try to do as part of this bug.

**Comment by mrenvoize** [comment]
Closing
