### ISSUE TITLE
Catalog search split button is a smaller click target now

### ISSUE THREAD

**Issue by oleonard** [jajm/koha-staff-interface-redesign#46]
<img width="526" alt="Screen Shot 2022-09-15 at 10 31 29 AM" src="https://user-images.githubusercontent.com/3648783/190431519-454c7082-d749-4998-b9f4-87f82e7214de.png">
<img width="627" alt="Screen Shot 2022-09-15 at 10 33 35 AM" src="https://user-images.githubusercontent.com/3648783/190431793-c0f93fdf-8907-4cee-ac7d-870405b3dfe8.png">

The split button for accessing catalog advanced search or item search is not as clear as before. I think it's important to keep the visual hints that it is a split button and not a regular dropdown menu. And I think it's going to be harder for users to aim for the smaller target of the down-arrow.

**Comment by oleonard** [comment]
![2022-09-15 12-13-01 2022-09-15 12_13_31](https://user-images.githubusercontent.com/3648783/190454798-9d7a7889-f79a-49cd-9542-fb978da650c3.gif)

**Comment by kfischer** [comment]
Looks good and like in @oleonard's video now.

**Comment by jajm** [comment]
Thanks for testing!
