### ISSUE TITLE
System preference <td> on  preferences.tt are the same color background as the <body> background

### ISSUE THREAD

**Issue by ricofreak** [jajm/koha-staff-interface-redesign#55]
If you search for system preferences the `<td>`'s have a background color (#f3f4f4) which is exactly the same as the `<body>` background. I end up losing my place as I cannot see where the `<td>` ends.

**Comment by ricofreak** [comment]
This actually effects most tables. It makes the table blend with the body background color. Do we need to add some kind of table border?

**Comment by mrenvoize** [comment]
Aha, I resolved this elsewhere by ensuring 'content' was inside a 'page-section'.. i.e. it had a white background... this is one I think we should all help with as follow-ups after push.. spread the load.

**Comment by mrenvoize** [comment]
See issue #45 and issue #22 for some further details around this @ricofreak

**Comment by mrenvoize** [comment]
Adding the 'page-section' class to the divs with 'prefs-tab' class yields this @ricofreak, does that work for you?

![screenshot-pro-mt38042-koha demo biblibre eu-2022 10 03-13_33_20](https://user-images.githubusercontent.com/557612/193577562-1c105d05-6985-4605-905d-8718240e6860.png)

**Comment by ricofreak** [comment]
Yes, that looks much better to me! Thanks!

**Comment by mrenvoize** [comment]
OK.. I'll add that as a bug on bugzilla now.. the screenshot was just a test I did locally.. I'll go ahead and work through the codebase adding page-section divs.

**Comment by mrenvoize** [comment]
See [bug 31758](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31758)
