### ISSUE TITLE
center-left alignment blink on hovering over .linktools

### ISSUE THREAD

**Issue by joubu** [jajm/koha-staff-interface-redesign#6]
To recreate:
Go to the add/edit items view
/cgi-bin/koha/cataloguing/additem.pl?op=edititem&biblionumber=46&itemnumber=95#edititem
Click on one cell of the table, go to "delete item", notice the alignment switch (center to left)

**Comment by joubu** [comment]
Same "blink" on this view for the breadcrumb.

**Comment by kfischer** [comment]
There is still something odd going on here.
* The dialog is really small with 100% view
* The highlighted entry you currently hover over is yellow background on yellow background - so not really highlighting, but vanishing.

**Comment by jajm** [comment]
> There is still something odd going on here.
> 
>     * The dialog is really small with 100% view
> 
>     * The highlighted entry you currently hover over is yellow background on yellow background - so not really highlighting, but vanishing.

It looks really similar to what's on master. Not a problem introduced by these patches IMO.

**Comment by kfischer** [comment]
I think you are right, I just compared versions. 
The issue I found is related to the line being the currently edited item. Then the background changes to yellow. Something for a future bug maybe.
Original issue is fixed then.
