### ISSUE TITLE
Form - wrong alignment for long label

### ISSUE THREAD

**Issue by joubu** [jajm/koha-staff-interface-redesign#7]
To recreate:
create or edit a city and notice that the "ZIP/Postal code: " label is wider than the other labels.

https://snipboard.io/5dvBSI.jpg

**Comment by jajm** [comment]
The last commit should fix this. See the attached screenshot:

![image](https://user-images.githubusercontent.com/306836/181741995-8555b48f-c20b-4f4f-9334-c61f5c2a4cc8.png)

It also moves the "This field is required" message to above the input

**Comment by kfischer** [comment]
This looks ok to me now.

**Comment by jajm** [comment]
Thanks for testing!
